### ISSUE TITLE
images not rotating at interval

### ISSUE THREAD

**Issue by aheath70** [custom-components/camera.multisource#12]
**Version of the custom_component**
0.3.0

**Describe the bug**
I have 3 images in the /share directory, wanting them to rotate through at 5 second intervals.

cameras.yaml file configured as follows:-
```
- platform: multisource
  name: "Pool Controller"
  interval: 5
  images:
    - /share/pc1.jpg
    - /share/pc2.jpg
    - /share/pc3.jpg
```

Images are rotating, but seem to be at some kind of random interval - sometimes they rotate through at 10-15 seconds, sometimes 60+ seconds before they rotate.

I have also tried name without the double quotes, and it makes no difference, images still display, but they don't rotate or rotate sporadically.

**log**
Not sure how to collect debug logs - happy to gather whatever is required if you can tell me how to do it.
